#!/bin/bash

msg="$*"

if [ -z "$msg" ]; then
    echo $0: need a commit message
    exit 1
fi

hugo || exit 1
(
    cd public
    git add .
    git commit -m "$msg"
)
git add .
git commit -m "$msg"
git push -u origin master --recurse-submodules=on-demand
