#!/bin/bash

cd $(dirname $0)

pushd ../events-list

bundle exec ./event-list.rb -o ../events-list-site/content/_index.md -a ../events-list-site/content/about/_index.md -j ../events-list-site/static/data.json && {
    popd
    ./deploy "automatic update at $(date)"
}
