#!/bin/bash

cd $(dirname $0)

pushd ../events-list

bundle exec ./event-list.rb --hugo-dir=../events-list-site/content -j ../events-list-site/static/data.json && {
    popd
    ./deploy "automatic update at $(date)"
}
